--------------------------------------------------------
--  파일이 생성됨 - 일요일-4월-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD_COMMENT
--------------------------------------------------------

  CREATE TABLE "COOK"."BOARD_COMMENT" 
   (	"BOARDCMT_NO" NUMBER(5,0), 
	"BOARD_NO" NUMBER(5,0), 
	"MEMBER_ID" VARCHAR2(12 BYTE), 
	"BOARDCMT_DETAIL" VARCHAR2(300 BYTE), 
	"BOARDCMT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "COOK"."BOARD_COMMENT"."BOARD_NO" IS '게시글번호';
   COMMENT ON COLUMN "COOK"."BOARD_COMMENT"."MEMBER_ID" IS '작성자';
   COMMENT ON COLUMN "COOK"."BOARD_COMMENT"."BOARDCMT_DETAIL" IS '댓글내용';
   COMMENT ON COLUMN "COOK"."BOARD_COMMENT"."BOARDCMT_DT" IS '댓글작성일자';
REM INSERTING into COOK.BOARD_COMMENT
SET DEFINE OFF;
Insert into COOK.BOARD_COMMENT (BOARDCMT_NO,BOARD_NO,MEMBER_ID,BOARDCMT_DETAIL,BOARDCMT_DT) values (1,1,'id1','댓글테스트입니다',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.BOARD_COMMENT (BOARDCMT_NO,BOARD_NO,MEMBER_ID,BOARDCMT_DETAIL,BOARDCMT_DT) values (2,1,'id1','댓글테스트입니다',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.BOARD_COMMENT (BOARDCMT_NO,BOARD_NO,MEMBER_ID,BOARDCMT_DETAIL,BOARDCMT_DT) values (3,1,'id1','댓글테스트입니다',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.BOARD_COMMENT (BOARDCMT_NO,BOARD_NO,MEMBER_ID,BOARDCMT_DETAIL,BOARDCMT_DT) values (4,1,'id1','댓글테스트입니다',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.BOARD_COMMENT (BOARDCMT_NO,BOARD_NO,MEMBER_ID,BOARDCMT_DETAIL,BOARDCMT_DT) values (5,1,'id1','댓글테스트입니다',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.BOARD_COMMENT (BOARDCMT_NO,BOARD_NO,MEMBER_ID,BOARDCMT_DETAIL,BOARDCMT_DT) values (6,1,'id1','댓글테스트입니다',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.BOARD_COMMENT (BOARDCMT_NO,BOARD_NO,MEMBER_ID,BOARDCMT_DETAIL,BOARDCMT_DT) values (7,1,'id1','댓글테스트입니다',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.BOARD_COMMENT (BOARDCMT_NO,BOARD_NO,MEMBER_ID,BOARDCMT_DETAIL,BOARDCMT_DT) values (8,1,'id1','댓글테스트입니다',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.BOARD_COMMENT (BOARDCMT_NO,BOARD_NO,MEMBER_ID,BOARDCMT_DETAIL,BOARDCMT_DT) values (9,1,'id1','댓글테스트입니다',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.BOARD_COMMENT (BOARDCMT_NO,BOARD_NO,MEMBER_ID,BOARDCMT_DETAIL,BOARDCMT_DT) values (10,1,'id1','댓글테스트입니다',to_date('21/03/31','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index BOARD_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COOK"."BOARD_COMMENT_PK" ON "COOK"."BOARD_COMMENT" ("BOARDCMT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD_COMMENT
--------------------------------------------------------

  ALTER TABLE "COOK"."BOARD_COMMENT" ADD CONSTRAINT "BOARD_COMMENT_PK" PRIMARY KEY ("BOARDCMT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COOK"."BOARD_COMMENT" MODIFY ("BOARDCMT_DETAIL" NOT NULL ENABLE);
  ALTER TABLE "COOK"."BOARD_COMMENT" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "COOK"."BOARD_COMMENT" MODIFY ("BOARD_NO" NOT NULL ENABLE);
  ALTER TABLE "COOK"."BOARD_COMMENT" MODIFY ("BOARDCMT_NO" NOT NULL ENABLE);
