--------------------------------------------------------
--  파일이 생성됨 - 일요일-4월-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "COOK"."BOARD" 
   (	"BOARD_NO" NUMBER(5,0), 
	"BOARD_TITLE" VARCHAR2(150 BYTE), 
	"MEMBER_ID" VARCHAR2(25 BYTE), 
	"BOARD_DETAIL" VARCHAR2(3000 BYTE), 
	"BOARD_DT" DATE, 
	"BOARD_CNT" NUMBER(5,0) DEFAULT 0, 
	"BOARD_REPORT_CNT" NUMBER(2,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "COOK"."BOARD"."BOARD_NO" IS '게시글번호';
   COMMENT ON COLUMN "COOK"."BOARD"."BOARD_TITLE" IS '게시글제목';
   COMMENT ON COLUMN "COOK"."BOARD"."MEMBER_ID" IS '작성자';
   COMMENT ON COLUMN "COOK"."BOARD"."BOARD_DETAIL" IS '게시글내용';
   COMMENT ON COLUMN "COOK"."BOARD"."BOARD_DT" IS '작성날짜';
   COMMENT ON COLUMN "COOK"."BOARD"."BOARD_CNT" IS '조회수';
   COMMENT ON COLUMN "COOK"."BOARD"."BOARD_REPORT_CNT" IS '신고횟수';
REM INSERTING into COOK.BOARD
SET DEFINE OFF;
Insert into COOK.BOARD (BOARD_NO,BOARD_TITLE,MEMBER_ID,BOARD_DETAIL,BOARD_DT,BOARD_CNT,BOARD_REPORT_CNT) values (1,'title','id1','detail1',to_date('21/03/31','RR/MM/DD'),0,0);
Insert into COOK.BOARD (BOARD_NO,BOARD_TITLE,MEMBER_ID,BOARD_DETAIL,BOARD_DT,BOARD_CNT,BOARD_REPORT_CNT) values (2,'title','id1','detail1',to_date('21/03/31','RR/MM/DD'),0,0);
Insert into COOK.BOARD (BOARD_NO,BOARD_TITLE,MEMBER_ID,BOARD_DETAIL,BOARD_DT,BOARD_CNT,BOARD_REPORT_CNT) values (3,'title','id1','detail1',to_date('21/03/31','RR/MM/DD'),0,0);
Insert into COOK.BOARD (BOARD_NO,BOARD_TITLE,MEMBER_ID,BOARD_DETAIL,BOARD_DT,BOARD_CNT,BOARD_REPORT_CNT) values (4,'title','id1','detail1',to_date('21/03/31','RR/MM/DD'),0,0);
Insert into COOK.BOARD (BOARD_NO,BOARD_TITLE,MEMBER_ID,BOARD_DETAIL,BOARD_DT,BOARD_CNT,BOARD_REPORT_CNT) values (5,'title','id1','detail1',to_date('21/03/31','RR/MM/DD'),0,0);
Insert into COOK.BOARD (BOARD_NO,BOARD_TITLE,MEMBER_ID,BOARD_DETAIL,BOARD_DT,BOARD_CNT,BOARD_REPORT_CNT) values (6,'title','id1','detail1',to_date('21/03/31','RR/MM/DD'),0,0);
Insert into COOK.BOARD (BOARD_NO,BOARD_TITLE,MEMBER_ID,BOARD_DETAIL,BOARD_DT,BOARD_CNT,BOARD_REPORT_CNT) values (7,'title','id1','detail1',to_date('21/03/31','RR/MM/DD'),0,0);
Insert into COOK.BOARD (BOARD_NO,BOARD_TITLE,MEMBER_ID,BOARD_DETAIL,BOARD_DT,BOARD_CNT,BOARD_REPORT_CNT) values (8,'title','id1','detail1',to_date('21/03/31','RR/MM/DD'),0,0);
Insert into COOK.BOARD (BOARD_NO,BOARD_TITLE,MEMBER_ID,BOARD_DETAIL,BOARD_DT,BOARD_CNT,BOARD_REPORT_CNT) values (9,'title','id1','detail1',to_date('21/03/31','RR/MM/DD'),0,0);
Insert into COOK.BOARD (BOARD_NO,BOARD_TITLE,MEMBER_ID,BOARD_DETAIL,BOARD_DT,BOARD_CNT,BOARD_REPORT_CNT) values (10,'title','id1','detail1',to_date('21/03/31','RR/MM/DD'),0,0);
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COOK"."BOARD_PK" ON "COOK"."BOARD" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "COOK"."BOARD" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COOK"."BOARD" MODIFY ("BOARD_DT" NOT NULL ENABLE);
  ALTER TABLE "COOK"."BOARD" MODIFY ("BOARD_DETAIL" NOT NULL ENABLE);
  ALTER TABLE "COOK"."BOARD" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "COOK"."BOARD" MODIFY ("BOARD_TITLE" NOT NULL ENABLE);
  ALTER TABLE "COOK"."BOARD" MODIFY ("BOARD_NO" NOT NULL ENABLE);
