--------------------------------------------------------
--  파일이 생성됨 - 일요일-4월-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QNA
--------------------------------------------------------

  CREATE TABLE "COOK"."QNA" 
   (	"QUESTION_NO" NUMBER(4,0), 
	"QUESTION_TITLE" VARCHAR2(150 BYTE), 
	"QUESTION_DETAIL" VARCHAR2(3000 BYTE), 
	"MEMBER_ID" VARCHAR2(12 BYTE), 
	"QUESTION_DT" DATE, 
	"QUESTION_ANS_DT" DATE DEFAULT null, 
	"QUESTION_ANS_DETAIL" VARCHAR2(3000 BYTE) DEFAULT null
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "COOK"."QNA"."QUESTION_NO" IS '문의번호';
   COMMENT ON COLUMN "COOK"."QNA"."QUESTION_TITLE" IS '문의제목';
   COMMENT ON COLUMN "COOK"."QNA"."QUESTION_DETAIL" IS '문의내용';
   COMMENT ON COLUMN "COOK"."QNA"."MEMBER_ID" IS '작성자';
   COMMENT ON COLUMN "COOK"."QNA"."QUESTION_DT" IS '문의작성날짜';
   COMMENT ON COLUMN "COOK"."QNA"."QUESTION_ANS_DT" IS '문의답변날짜';
   COMMENT ON COLUMN "COOK"."QNA"."QUESTION_ANS_DETAIL" IS '문의답변내용';
REM INSERTING into COOK.QNA
SET DEFINE OFF;
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (1,'이거 어떻게 올려요?','레시피 어떻게 올려요? 모르겠는데','id1',to_date('21/03/31','RR/MM/DD'),null,null);
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (2,'이거 어떻게 올려요?','레시피 어떻게 올려요? 모르겠는데','id1',to_date('21/03/31','RR/MM/DD'),null,null);
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (3,'이거 어떻게 올려요?','레시피 어떻게 올려요? 모르겠는데','id1',to_date('21/03/31','RR/MM/DD'),null,null);
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (4,'이거 어떻게 올려요?','레시피 어떻게 올려요? 모르겠는데','id1',to_date('21/03/31','RR/MM/DD'),null,null);
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (5,'이거 어떻게 올려요?','레시피 어떻게 올려요? 모르겠는데','id1',to_date('21/03/31','RR/MM/DD'),null,null);
--------------------------------------------------------
--  DDL for Index QNA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COOK"."QNA_PK" ON "COOK"."QNA" ("QUESTION_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "COOK"."QNA" ADD CONSTRAINT "QNA_PK" PRIMARY KEY ("QUESTION_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COOK"."QNA" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "COOK"."QNA" MODIFY ("QUESTION_DETAIL" NOT NULL ENABLE);
  ALTER TABLE "COOK"."QNA" MODIFY ("QUESTION_TITLE" NOT NULL ENABLE);
  ALTER TABLE "COOK"."QNA" MODIFY ("QUESTION_NO" NOT NULL ENABLE);
