--------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-23-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QNA
--------------------------------------------------------

  CREATE TABLE "COOK"."QNA" 
   (	"QUESTION_NO" NUMBER(4,0), 
	"QUESTION_TITLE" VARCHAR2(150 BYTE), 
	"QUESTION_DETAIL" VARCHAR2(3000 BYTE), 
	"MEMBER_ID" VARCHAR2(12 BYTE), 
	"QUESTION_DT" DATE, 
	"QUESTION_ANS_DT" DATE DEFAULT null, 
	"QUESTION_ANS_DETAIL" VARCHAR2(3000 BYTE) DEFAULT null
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "COOK"."QNA"."QUESTION_NO" IS '문의번호';
   COMMENT ON COLUMN "COOK"."QNA"."QUESTION_TITLE" IS '문의제목';
   COMMENT ON COLUMN "COOK"."QNA"."QUESTION_DETAIL" IS '문의내용';
   COMMENT ON COLUMN "COOK"."QNA"."MEMBER_ID" IS '작성자';
   COMMENT ON COLUMN "COOK"."QNA"."QUESTION_DT" IS '문의작성날짜';
   COMMENT ON COLUMN "COOK"."QNA"."QUESTION_ANS_DT" IS '문의답변날짜';
   COMMENT ON COLUMN "COOK"."QNA"."QUESTION_ANS_DETAIL" IS '문의답변내용';
REM INSERTING into COOK.QNA
SET DEFINE OFF;
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (2,'초밥 만드는 방법은 없나요?','초밥도 한 번 만들어보고 싶어요','shtjdqhd',to_date('21/03/28','RR/MM/DD'),null,null);
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (3,'회원탈퇴 방법','알려주세요','rlatnals',to_date('21/04/01','RR/MM/DD'),null,null);
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (4,'이메일 주소 변경하고 싶어요','이메일 변경 가능한가요?','rlatnals',to_date('21/04/03','RR/MM/DD'),null,null);
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (5,'자동로그인이 뭔가요?','제 아이디 안전한 거에요?','dhstndls',to_date('21/04/03','RR/MM/DD'),null,null);
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (6,'레시피 삭제는 어떻게 해요?','맘에 안들어요 다시 올리고 싶어요','shtjdqhd',to_date('21/04/04','RR/MM/DD'),null,null);
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (7,'스크랩 어떻게 하는 건가요?','저장하고 싶은 레시피가 있는데 모르겠어요ㅠ','qkrdkfks',to_date('21/04/08','RR/MM/DD'),null,null);
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (1,'레시피 어떻게 올려요?','저도 맛있는 내용 공유하고 싶습니다!','qkrdkfks',to_date('21/03/15','RR/MM/DD'),null,null);
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (8,'닉네임도 변경 가능해요?','잘못만들었어요','shtjdqhd',to_date('21/04/11','RR/MM/DD'),null,null);
Insert into COOK.QNA (QUESTION_NO,QUESTION_TITLE,QUESTION_DETAIL,MEMBER_ID,QUESTION_DT,QUESTION_ANS_DT,QUESTION_ANS_DETAIL) values (9,'회원탈퇴하면 제 정보는 어떻게 되는 건가요?','완전히 사라지나요?','qkrdkfks',to_date('21/04/22','RR/MM/DD'),null,null);
--------------------------------------------------------
--  DDL for Index QNA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COOK"."QNA_PK" ON "COOK"."QNA" ("QUESTION_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "COOK"."QNA" ADD CONSTRAINT "QNA_PK" PRIMARY KEY ("QUESTION_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COOK"."QNA" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "COOK"."QNA" MODIFY ("QUESTION_DETAIL" NOT NULL ENABLE);
  ALTER TABLE "COOK"."QNA" MODIFY ("QUESTION_TITLE" NOT NULL ENABLE);
  ALTER TABLE "COOK"."QNA" MODIFY ("QUESTION_NO" NOT NULL ENABLE);
