--------------------------------------------------------
--  파일이 생성됨 - 일요일-4월-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RECIPE_INGRE
--------------------------------------------------------

  CREATE TABLE "COOK"."RECIPE_INGRE" 
   (	"RECIPE_NO" NUMBER(6,0), 
	"RECIPE_INGRE_NO" NUMBER(2,0), 
	"RECIPE_INGRE_NAME" VARCHAR2(30 BYTE), 
	"RECIPE_INGRE_METERING" VARCHAR2(10 BYTE), 
	"RECIPE_INGRE_TYPE" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "COOK"."RECIPE_INGRE"."RECIPE_NO" IS '레시피번호';
   COMMENT ON COLUMN "COOK"."RECIPE_INGRE"."RECIPE_INGRE_NO" IS '재료번호';
   COMMENT ON COLUMN "COOK"."RECIPE_INGRE"."RECIPE_INGRE_NAME" IS '재료명';
   COMMENT ON COLUMN "COOK"."RECIPE_INGRE"."RECIPE_INGRE_METERING" IS '계량';
   COMMENT ON COLUMN "COOK"."RECIPE_INGRE"."RECIPE_INGRE_TYPE" IS '재료타입';
REM INSERTING into COOK.RECIPE_INGRE
SET DEFINE OFF;
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (1,1,'김치','10포기','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (1,2,'스팸','반 통','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (1,3,'물','100리터','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (2,4,'광어회','한마리','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (2,5,'밥','3공기','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (2,6,'간장','20방울','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,7,'닭','한마리','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,8,'감자','한개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,9,'고추장','두스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (4,10,'떡볶이 떡','300g','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (4,11,'어묵','5장','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (4,12,'로제파스타소스','10큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (5,13,'냉면사리','1포','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (5,14,'냉면육수','한 통','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (5,15,'고추장','한 큰술','양념');
--------------------------------------------------------
--  DDL for Index RECIPE_INGRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COOK"."RECIPE_INGRE_PK" ON "COOK"."RECIPE_INGRE" ("RECIPE_NO", "RECIPE_INGRE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RECIPE_INGRE
--------------------------------------------------------

  ALTER TABLE "COOK"."RECIPE_INGRE" ADD CONSTRAINT "RECIPE_INGRE_PK" PRIMARY KEY ("RECIPE_NO", "RECIPE_INGRE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COOK"."RECIPE_INGRE" MODIFY ("RECIPE_INGRE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_INGRE" MODIFY ("RECIPE_INGRE_NAME" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_INGRE" MODIFY ("RECIPE_INGRE_NO" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_INGRE" MODIFY ("RECIPE_NO" NOT NULL ENABLE);
