--------------------------------------------------------
--  파일이 생성됨 - 일요일-4월-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RECIPE_COMMENT
--------------------------------------------------------

  CREATE TABLE "COOK"."RECIPE_COMMENT" 
   (	"RECIPECMT_NO" NUMBER(2,0), 
	"RECIPE_NO" NUMBER(6,0), 
	"MEMBER_ID" VARCHAR2(12 BYTE), 
	"RECIPECMT_DETAIL" VARCHAR2(500 BYTE), 
	"RECIPECMT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "COOK"."RECIPE_COMMENT"."RECIPECMT_NO" IS '댓글번호';
   COMMENT ON COLUMN "COOK"."RECIPE_COMMENT"."RECIPE_NO" IS '레시피번호';
   COMMENT ON COLUMN "COOK"."RECIPE_COMMENT"."MEMBER_ID" IS '댓글작성자';
   COMMENT ON COLUMN "COOK"."RECIPE_COMMENT"."RECIPECMT_DETAIL" IS '댓글내용';
   COMMENT ON COLUMN "COOK"."RECIPE_COMMENT"."RECIPECMT_DT" IS '댓글작성날짜';
REM INSERTING into COOK.RECIPE_COMMENT
SET DEFINE OFF;
Insert into COOK.RECIPE_COMMENT (RECIPECMT_NO,RECIPE_NO,MEMBER_ID,RECIPECMT_DETAIL,RECIPECMT_DT) values (1,1,'id1','우와~ 짱이다!',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.RECIPE_COMMENT (RECIPECMT_NO,RECIPE_NO,MEMBER_ID,RECIPECMT_DETAIL,RECIPECMT_DT) values (2,1,'id1','우와~ 짱이다!',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.RECIPE_COMMENT (RECIPECMT_NO,RECIPE_NO,MEMBER_ID,RECIPECMT_DETAIL,RECIPECMT_DT) values (3,1,'id1','우와~ 짱이다!',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.RECIPE_COMMENT (RECIPECMT_NO,RECIPE_NO,MEMBER_ID,RECIPECMT_DETAIL,RECIPECMT_DT) values (4,1,'id1','우와~ 짱이다!',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.RECIPE_COMMENT (RECIPECMT_NO,RECIPE_NO,MEMBER_ID,RECIPECMT_DETAIL,RECIPECMT_DT) values (5,1,'id1','우와~ 짱이다!',to_date('21/03/31','RR/MM/DD'));
Insert into COOK.RECIPE_COMMENT (RECIPECMT_NO,RECIPE_NO,MEMBER_ID,RECIPECMT_DETAIL,RECIPECMT_DT) values (6,5,'id4','랭면은 역시 옥천랭면이라우',to_date('21/03/31','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index RECIPE_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COOK"."RECIPE_COMMENT_PK" ON "COOK"."RECIPE_COMMENT" ("RECIPECMT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RECIPE_COMMENT
--------------------------------------------------------

  ALTER TABLE "COOK"."RECIPE_COMMENT" ADD CONSTRAINT "RECIPE_COMMENT_PK" PRIMARY KEY ("RECIPECMT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COOK"."RECIPE_COMMENT" MODIFY ("RECIPECMT_DETAIL" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_COMMENT" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_COMMENT" MODIFY ("RECIPE_NO" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_COMMENT" MODIFY ("RECIPECMT_NO" NOT NULL ENABLE);
