--------------------------------------------------------
--  파일이 생성됨 - 일요일-4월-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RECIPE_PROCESS
--------------------------------------------------------

  CREATE TABLE "COOK"."RECIPE_PROCESS" 
   (	"RECIPE_NO" NUMBER(6,0), 
	"RECIPE_STEP_NO" NUMBER(2,0), 
	"RECIPE_STEP_TEXT" VARCHAR2(300 BYTE), 
	"RECIPE_STEP_IMG" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "COOK"."RECIPE_PROCESS"."RECIPE_NO" IS '레시피번호';
   COMMENT ON COLUMN "COOK"."RECIPE_PROCESS"."RECIPE_STEP_NO" IS '조리과정순번';
   COMMENT ON COLUMN "COOK"."RECIPE_PROCESS"."RECIPE_STEP_TEXT" IS '조리내용';
   COMMENT ON COLUMN "COOK"."RECIPE_PROCESS"."RECIPE_STEP_IMG" IS '조리이미지
';
REM INSERTING into COOK.RECIPE_PROCESS
SET DEFINE OFF;
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (1,1,'물을끓여요','water.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (1,2,'김치을 넣어요','putkimchi.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (1,3,'스팸을 넣어요','putspam.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (2,1,'밥을 해요','img1.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (2,2,'회를 썰어요','img2.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (2,3,'회를 밥위에 올려요','img3.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (3,1,'닭을 손질 해요','img1.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (3,2,'물을 끓여요','img2.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (3,3,'양념하고 팔팔 끓여요','img3.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (4,1,'물을끓일 떄 양념과 물엿을 넣어줍니다','waterboiling.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (4,2,'물이 끓으면 준비된 떡과 어묵을 넣어줍니다','putddok.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (4,3,'떡이 말랑말랑해지면 완성','complete.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (5,1,'물을끓여요','hotwater.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (5,2,'면을 삶아요','noodle.png');
Insert into COOK.RECIPE_PROCESS (RECIPE_NO,RECIPE_STEP_NO,RECIPE_STEP_TEXT,RECIPE_STEP_IMG) values (5,3,'육수를 넣어요','uksu.png');
--------------------------------------------------------
--  DDL for Index RECIPE_PROCESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COOK"."RECIPE_PROCESS_PK" ON "COOK"."RECIPE_PROCESS" ("RECIPE_NO", "RECIPE_STEP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RECIPE_PROCESS
--------------------------------------------------------

  ALTER TABLE "COOK"."RECIPE_PROCESS" ADD CONSTRAINT "RECIPE_PROCESS_PK" PRIMARY KEY ("RECIPE_NO", "RECIPE_STEP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COOK"."RECIPE_PROCESS" MODIFY ("RECIPE_STEP_IMG" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_PROCESS" MODIFY ("RECIPE_STEP_TEXT" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_PROCESS" MODIFY ("RECIPE_STEP_NO" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_PROCESS" MODIFY ("RECIPE_NO" NOT NULL ENABLE);
