--------------------------------------------------------
--  파일이 생성됨 - 일요일-4월-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RECIPE_INFO
--------------------------------------------------------

  CREATE TABLE "COOK"."RECIPE_INFO" 
   (	"RECIPE_NO" NUMBER(6,0), 
	"MEMBER_ID" VARCHAR2(12 BYTE), 
	"RECIPE_NAME" VARCHAR2(30 BYTE), 
	"RECIPE_INTRO" VARCHAR2(400 BYTE), 
	"RECIPE_CATEGORY" VARCHAR2(15 BYTE), 
	"RECIPE_TIME" NUMBER(3,0), 
	"RECIPE_LEVEL" NUMBER(1,0), 
	"RECIPE_IMG" VARCHAR2(20 BYTE), 
	"RECIPE_SCRAP_CNT_CNT" NUMBER(4,0) DEFAULT 0, 
	"RECIPE_CNT" NUMBER(5,0) DEFAULT 0, 
	"RECIPE_DT" DATE, 
	"RECIPE_STATUS" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "COOK"."RECIPE_INFO"."RECIPE_NO" IS '레시피번호';
   COMMENT ON COLUMN "COOK"."RECIPE_INFO"."MEMBER_ID" IS '작성자아이디';
   COMMENT ON COLUMN "COOK"."RECIPE_INFO"."RECIPE_NAME" IS '레시피이름';
   COMMENT ON COLUMN "COOK"."RECIPE_INFO"."RECIPE_INTRO" IS '레시피소개글';
   COMMENT ON COLUMN "COOK"."RECIPE_INFO"."RECIPE_CATEGORY" IS '카테고리';
   COMMENT ON COLUMN "COOK"."RECIPE_INFO"."RECIPE_TIME" IS '조리시간';
   COMMENT ON COLUMN "COOK"."RECIPE_INFO"."RECIPE_LEVEL" IS '조리난이도';
   COMMENT ON COLUMN "COOK"."RECIPE_INFO"."RECIPE_IMG" IS '대표이미지';
   COMMENT ON COLUMN "COOK"."RECIPE_INFO"."RECIPE_SCRAP_CNT_CNT" IS '스크랩수';
   COMMENT ON COLUMN "COOK"."RECIPE_INFO"."RECIPE_CNT" IS '레시피조회수';
   COMMENT ON COLUMN "COOK"."RECIPE_INFO"."RECIPE_DT" IS '작성일자';
   COMMENT ON COLUMN "COOK"."RECIPE_INFO"."RECIPE_STATUS" IS '레시피상태';
REM INSERTING into COOK.RECIPE_INFO
SET DEFINE OFF;
Insert into COOK.RECIPE_INFO (RECIPE_NO,MEMBER_ID,RECIPE_NAME,RECIPE_INTRO,RECIPE_CATEGORY,RECIPE_TIME,RECIPE_LEVEL,RECIPE_IMG,RECIPE_SCRAP_CNT_CNT,RECIPE_CNT,RECIPE_DT,RECIPE_STATUS) values (1,'id1','맛있는 김치찌개','김치찌개는 스팸이지','한식',10,3,'kimchizzigae.png',0,0,to_date('21/03/31','RR/MM/DD'),0);
Insert into COOK.RECIPE_INFO (RECIPE_NO,MEMBER_ID,RECIPE_NAME,RECIPE_INTRO,RECIPE_CATEGORY,RECIPE_TIME,RECIPE_LEVEL,RECIPE_IMG,RECIPE_SCRAP_CNT_CNT,RECIPE_CNT,RECIPE_DT,RECIPE_STATUS) values (2,'id3','초밥','초밥엔 회','한식',10,3,'chobab.png',0,0,to_date('21/03/31','RR/MM/DD'),0);
Insert into COOK.RECIPE_INFO (RECIPE_NO,MEMBER_ID,RECIPE_NAME,RECIPE_INTRO,RECIPE_CATEGORY,RECIPE_TIME,RECIPE_LEVEL,RECIPE_IMG,RECIPE_SCRAP_CNT_CNT,RECIPE_CNT,RECIPE_DT,RECIPE_STATUS) values (3,'id3','닭볶음탕','닭','한식',10,3,'iloveyou.png',0,0,to_date('21/03/31','RR/MM/DD'),0);
Insert into COOK.RECIPE_INFO (RECIPE_NO,MEMBER_ID,RECIPE_NAME,RECIPE_INTRO,RECIPE_CATEGORY,RECIPE_TIME,RECIPE_LEVEL,RECIPE_IMG,RECIPE_SCRAP_CNT_CNT,RECIPE_CNT,RECIPE_DT,RECIPE_STATUS) values (4,'id2','로제떡볶이','로제떡볶이 황금 레시피','분식',15,1,'roseddokbokki.png',0,0,to_date('21/03/31','RR/MM/DD'),0);
Insert into COOK.RECIPE_INFO (RECIPE_NO,MEMBER_ID,RECIPE_NAME,RECIPE_INTRO,RECIPE_CATEGORY,RECIPE_TIME,RECIPE_LEVEL,RECIPE_IMG,RECIPE_SCRAP_CNT_CNT,RECIPE_CNT,RECIPE_DT,RECIPE_STATUS) values (5,'id4','칡냉면','냉면은 역시 칡 냉면이지~!','한식',15,3,'lang.png',0,0,to_date('21/03/31','RR/MM/DD'),0);
--------------------------------------------------------
--  DDL for Index RECIPE_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COOK"."RECIPE_INFO_PK" ON "COOK"."RECIPE_INFO" ("RECIPE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RECIPE_INFO
--------------------------------------------------------

  ALTER TABLE "COOK"."RECIPE_INFO" ADD CONSTRAINT "RECIPE_INFO_PK" PRIMARY KEY ("RECIPE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COOK"."RECIPE_INFO" MODIFY ("RECIPE_IMG" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_INFO" MODIFY ("RECIPE_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_INFO" MODIFY ("RECIPE_TIME" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_INFO" MODIFY ("RECIPE_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_INFO" MODIFY ("RECIPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_INFO" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_INFO" MODIFY ("RECIPE_NO" NOT NULL ENABLE);
