--------------------------------------------------------
--  파일이 생성됨 - 금요일-4월-23-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RECIPE_INGRE
--------------------------------------------------------

  CREATE TABLE "COOK"."RECIPE_INGRE" 
   (	"RECIPE_NO" NUMBER(6,0), 
	"RECIPE_INGRE_NO" NUMBER(2,0), 
	"RECIPE_INGRE_NAME" VARCHAR2(30 BYTE), 
	"RECIPE_INGRE_METERING" VARCHAR2(20 BYTE), 
	"RECIPE_INGRE_TYPE" VARCHAR2(9 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "COOK"."RECIPE_INGRE"."RECIPE_NO" IS '레시피번호';
   COMMENT ON COLUMN "COOK"."RECIPE_INGRE"."RECIPE_INGRE_NO" IS '재료번호';
   COMMENT ON COLUMN "COOK"."RECIPE_INGRE"."RECIPE_INGRE_NAME" IS '재료명';
   COMMENT ON COLUMN "COOK"."RECIPE_INGRE"."RECIPE_INGRE_METERING" IS '계량';
   COMMENT ON COLUMN "COOK"."RECIPE_INGRE"."RECIPE_INGRE_TYPE" IS '재료타입';
REM INSERTING into COOK.RECIPE_INGRE
SET DEFINE OFF;
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (7,1,'프랑크소세지','1개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (7,2,'마늘쫑','1단','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (7,3,'간장','2스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (7,5,'참기름','1스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (7,6,'통깨',null,'양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (8,1,'팽이버섯','1봉','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (8,2,'대파','1줌','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (8,3,'양파','반개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (8,4,'달걀','한개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (8,5,'참기름','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (8,6,'통깨','적당히','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (8,7,'간장','2숟가락','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (8,8,'굴소스','반숟가락','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (8,9,'설탕','반숟가락','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (8,10,'맛술','2숟가락','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (7,4,'올리고당','1스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (8,11,'물','3큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (9,1,'새송이버섯','2개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (9,2,'버터','10g','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (9,3,'맛술','1.5큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (9,4,'식용유','적당히','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (9,5,'진간장','1.5큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (4,2,'우엉','1/3뿌리','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (4,3,'쇠고기','30g','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (4,4,'당근','1/4개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (4,5,'후춧가루','조금','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (4,6,'간장','2큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (4,7,'청주','1큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (4,8,'설탕','1큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (4,9,'밥','1공기','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (5,1,'실파','2단','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (5,2,'까나리액젓','1컵','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (5,3,'다진마늘','1과 1/2작은술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (5,4,'깨소금','2큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (5,5,'고춧가루','1컵','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (5,6,'설탕','2큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (5,7,'소금','약간','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (4,1,'유부','5장','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (5,8,'다진생강','1작은술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,1,'가래떡','500g','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,2,'쇠고기 육수','8컵','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,3,'대파','1뿌리','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,4,'쇠고기','100g','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,5,'계란','1개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,6,'소금','약간','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,7,'후춧가루','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,8,'설탕','1/2큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,9,'다진파','2작은술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,10,'다진마늘','1작은술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,11,'깨소금','1작은술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,12,'참기름','1작은술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (6,13,'간장','1큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (1,1,'무','1/4개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (2,2,'생크림','1과 1/2컵','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (1,2,'고춧가루','1작은술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (1,3,'식초','1과 1/2큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (1,4,'설탕','1과 2/3큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (1,5,'깨소금','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (1,6,'참기름','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (1,7,'다진파','1작은술','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (1,8,'다진마늘','1/2작은술','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (1,9,'소금','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (2,1,'파스타','200g','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (2,3,'양파','2/1개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (2,4,'후춧가루','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (2,5,'다진마늘','1작은술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (2,6,'베이컨','6장','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (2,7,'우유','1/2컵','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (2,8,'버터','2큰술','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (2,9,'소금','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,1,'두부','1팩','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,2,'계란','1개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,3,'청정원어장','2큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,4,'고춧가루','1~2큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,5,'깨소금','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,6,'양파','1/2개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,7,'미더덕','약간','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,8,'바지락','약간','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,9,'잔새우','약간','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,11,'멸치','한줌','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (3,10,'다시마','1장','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (10,1,'새우','20마리','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (10,2,'올리고당','2큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (10,3,'파슬리','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (10,4,'올리브유','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (10,5,'버터','20g','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (10,6,'다진마늘','1큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (10,7,'후추','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (10,8,'소금','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (11,1,'연두부','1팩','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (11,2,'어린잎채소','1/2줌','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (11,3,'파프리카','약간','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (11,4,'양파','약간','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (11,5,'간장','2.5T','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (11,6,'식초','1.5T','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (11,7,'설탕','1T','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (11,8,'다진마늘','1T','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (11,9,'참기름','1t','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (11,10,'통깨','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (12,1,'고구마',null,'주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (12,2,'버터',null,'부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (12,3,'꿀',null,'양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (12,4,'피자치즈',null,'부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (13,1,'떡볶이떡',null,'주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (13,2,'베이컨',null,'주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (13,3,'소금',null,'양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (13,4,'블랙페이퍼',null,'양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (14,1,'후랑크소시지','4','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (14,2,'양파','1/4개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (14,3,'후춧가루','약간','소스');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (14,4,'머스타드소스',null,'소스');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (14,5,'피자치즈',null,'주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (14,6,'소금',null,'양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (14,7,'케첩',null,'양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (14,8,'파슬리가루',null,'양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (15,1,'버터 또는 식용유','100g','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (15,2,'계란','2개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (15,3,'설탕','100g','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (15,4,'소금','2꼬집','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (15,5,'박력분','180g','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (15,6,'코코아파우더','50g','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (15,7,'베이킹파우더','4g','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (15,8,'슈가파우더',null,'부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (16,1,'고구마','1개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (16,2,'모짜렐라치즈','1컵','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (16,3,'물','50ml','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (16,4,'설탕','1스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (16,5,'소금','1/3스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (16,6,'찹쌀가루','1스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (17,1,'느타리버섯','200g','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (17,2,'표고버섯','4개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (17,3,'쪽파','2대','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (17,4,'들깨가루','2Ts','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (17,5,'멸치액젓','1Ts','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (17,6,'비정제 황설탕','1/2ts','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (17,7,'들기름','2ts','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (18,1,'곤약','500g','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (18,2,'식초','2숟갈','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (18,3,'물','250ml','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (18,4,'간장','5숟갈','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (18,5,'올리고당','2숟갈','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (18,6,'다진마늘','1숟갈','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (19,1,'꿀호떡','4개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (19,2,'치즈','2개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (19,3,'후추','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (19,4,'버터','1T','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (19,5,'계란','2개','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (20,1,'양파','1개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (20,2,'햄','조금','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (21,1,'콩나물','3줌','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (21,2,'대파','적당량','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (21,3,'고춧가루','1스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (21,4,'다진마늘','1/2스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (21,5,'굴소스','적당량','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (21,6,'사각어묵','1장','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (21,7,'당근','1토막','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (21,8,'양파','1토막','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (21,9,'고춧가루','1스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (22,1,'비비고김치콩비지찌개','1봉','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (22,2,'콩100%국산숙주','70g','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (22,3,'홍고추','1/2개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (22,4,'밀가루','100g','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (22,5,'삶은고사리','70g','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (22,6,'청양고추','1개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (22,7,'대파','1.2개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,1,'골뱅이','1캔(400g짜리)','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,2,'당근','1/2개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,3,'양파','1/2개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,4,'오이','1/2개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,5,'진미채 또는 북어채','적당량','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,6,'깻잎','취향껏','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,7,'대파','1/2대','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,8,'청양고추','취향껏','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,9,'소면','1줌','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,10,'고추장','3.5큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,11,'통깨','적당량','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,12,'고운 고춧가루','1큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,13,'설탕','3.5큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,14,'식초','3.5큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,15,'다진 마늘','1큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (23,16,'참기름','1큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (24,1,'모닝빵','6개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (24,2,'옥수수콘','1컵','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (24,3,'피자치즈','70g','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (24,4,'마요네즈','1스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (24,5,'허니 머스터드','1스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (24,6,'후춧가루','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (25,1,'식빵','2장','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (25,2,'베이컨','2줄','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (25,3,'계란','2개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (25,4,'슬라이스치즈','2장','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (25,5,'파슬리가루','약간','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (25,6,'딸기잼','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (26,1,'황태채','1줌','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (26,2,'설탕','1/2스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (26,3,'버터','2스푼','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (26,4,'파슬리가루','톡톡','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (27,1,'스트링치즈','4개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (27,2,'밀가루',null,'부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (27,3,'파슬리가루',null,'부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (27,4,'계란','1개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (27,5,'빵가루',null,'부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (28,1,'달걀','4개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (28,2,'슬라이스햄','8장','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (28,3,'슬라이스치즈','2장','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (28,4,'오이','1/2개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (28,5,'녹말가루','1Ts','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (28,6,'우유','0.5Ts','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (28,7,'식용유','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (28,8,'마요네즈','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (28,9,'오레가노','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (29,1,'닭(볶음용)','1마리','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (29,2,'당근',null,'부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (29,3,'마늘',null,'부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (29,4,'간장',null,'양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (29,5,'양파',null,'양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (29,6,'대파',null,'양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (29,7,'참기름',null,'양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,1,'닭가슴살','1조각','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,2,'완숙 토마토','1개','주재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,3,'양파','1/2개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,4,'당근','1/2개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,5,'양송이버섯','2개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,6,'브로콜리','1/3개','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,7,'마늘','2톨','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,8,'베이컨','2줄','부재료');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,9,'토모토 페이스트','3큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,10,'버터','1큰술','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,11,'월계수잎','1장','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,12,'바질','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,13,'청주','적당량','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,14,'소금','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,15,'후추','약간','양념');
Insert into COOK.RECIPE_INGRE (RECIPE_NO,RECIPE_INGRE_NO,RECIPE_INGRE_NAME,RECIPE_INGRE_METERING,RECIPE_INGRE_TYPE) values (30,16,'오일','적당량','양념');
--------------------------------------------------------
--  DDL for Index RECIPE_INGRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COOK"."RECIPE_INGRE_PK" ON "COOK"."RECIPE_INGRE" ("RECIPE_NO", "RECIPE_INGRE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RECIPE_INGRE
--------------------------------------------------------

  ALTER TABLE "COOK"."RECIPE_INGRE" ADD CONSTRAINT "RECIPE_INGRE_PK" PRIMARY KEY ("RECIPE_NO", "RECIPE_INGRE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COOK"."RECIPE_INGRE" MODIFY ("RECIPE_INGRE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_INGRE" MODIFY ("RECIPE_INGRE_NAME" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_INGRE" MODIFY ("RECIPE_INGRE_NO" NOT NULL ENABLE);
  ALTER TABLE "COOK"."RECIPE_INGRE" MODIFY ("RECIPE_NO" NOT NULL ENABLE);
