--------------------------------------------------------
--  파일이 생성됨 - 월요일-4월-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REPORT
--------------------------------------------------------

  CREATE TABLE "COOK"."REPORT" 
   (	"REPORT_NO" NUMBER(4,0), 
	"REPORT_TITLE" VARCHAR2(150 BYTE), 
	"REPORT_DETAIL" VARCHAR2(3000 BYTE), 
	"MEMBER_ID" VARCHAR2(12 BYTE), 
	"BOARD_NO" NUMBER(5,0), 
	"REPORT_STATUS" NUMBER(1,0) DEFAULT 0, 
	"REPORT_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "COOK"."REPORT"."REPORT_NO" IS '신고번호';
   COMMENT ON COLUMN "COOK"."REPORT"."REPORT_TITLE" IS '신고제목';
   COMMENT ON COLUMN "COOK"."REPORT"."REPORT_DETAIL" IS '신고내용';
   COMMENT ON COLUMN "COOK"."REPORT"."MEMBER_ID" IS '신고작성자';
   COMMENT ON COLUMN "COOK"."REPORT"."BOARD_NO" IS '게시물번호';
   COMMENT ON COLUMN "COOK"."REPORT"."REPORT_STATUS" IS '신고상태';
   COMMENT ON COLUMN "COOK"."REPORT"."REPORT_DT" IS '신고날짜';
REM INSERTING into COOK.REPORT
SET DEFINE OFF;
Insert into COOK.REPORT (REPORT_NO,REPORT_TITLE,REPORT_DETAIL,MEMBER_ID,BOARD_NO,REPORT_STATUS,REPORT_DT) values (1,'이 사람 게시물 똑같은 거 계속 올려요','삭제 좀 해주세요 계속 똑같은 말 올려요','id1',1,0,to_date('21/03/31','RR/MM/DD'));
Insert into COOK.REPORT (REPORT_NO,REPORT_TITLE,REPORT_DETAIL,MEMBER_ID,BOARD_NO,REPORT_STATUS,REPORT_DT) values (2,'이 사람 게시물 똑같은 거 계속 올려요','삭제 좀 해주세요 계속 똑같은 말 올려요','id1',1,0,to_date('21/03/31','RR/MM/DD'));
Insert into COOK.REPORT (REPORT_NO,REPORT_TITLE,REPORT_DETAIL,MEMBER_ID,BOARD_NO,REPORT_STATUS,REPORT_DT) values (3,'이 사람 게시물 똑같은 거 계속 올려요','삭제 좀 해주세요 계속 똑같은 말 올려요','id1',1,0,to_date('21/03/31','RR/MM/DD'));
Insert into COOK.REPORT (REPORT_NO,REPORT_TITLE,REPORT_DETAIL,MEMBER_ID,BOARD_NO,REPORT_STATUS,REPORT_DT) values (4,'이 사람 게시물 똑같은 거 계속 올려요','삭제 좀 해주세요 계속 똑같은 말 올려요','id1',1,0,to_date('21/03/31','RR/MM/DD'));
Insert into COOK.REPORT (REPORT_NO,REPORT_TITLE,REPORT_DETAIL,MEMBER_ID,BOARD_NO,REPORT_STATUS,REPORT_DT) values (5,'이 사람 게시물 똑같은 거 계속 올려요','삭제 좀 해주세요 계속 똑같은 말 올려요','id1',1,0,to_date('21/03/31','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index REPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COOK"."REPORT_PK" ON "COOK"."REPORT" ("REPORT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "COOK"."REPORT" ADD CONSTRAINT "REPORT_PK" PRIMARY KEY ("REPORT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COOK"."REPORT" MODIFY ("BOARD_NO" NOT NULL ENABLE);
  ALTER TABLE "COOK"."REPORT" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "COOK"."REPORT" MODIFY ("REPORT_DETAIL" NOT NULL ENABLE);
  ALTER TABLE "COOK"."REPORT" MODIFY ("REPORT_TITLE" NOT NULL ENABLE);
  ALTER TABLE "COOK"."REPORT" MODIFY ("REPORT_NO" NOT NULL ENABLE);
