--------------------------------------------------------
--  파일이 생성됨 - 월요일-4월-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SCRAP
--------------------------------------------------------

  CREATE TABLE "COOK"."SCRAP" 
   (	"SCRAP_NO" NUMBER(5,0), 
	"MEMBER_ID" VARCHAR2(12 BYTE), 
	"RECIPE_NO" NUMBER(6,0), 
	"SCRAP_DT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "COOK"."SCRAP"."SCRAP_NO" IS '스크랩번호';
   COMMENT ON COLUMN "COOK"."SCRAP"."MEMBER_ID" IS '아이디';
   COMMENT ON COLUMN "COOK"."SCRAP"."RECIPE_NO" IS '레시피번호';
   COMMENT ON COLUMN "COOK"."SCRAP"."SCRAP_DT" IS '스크랩날짜';
REM INSERTING into COOK.SCRAP
SET DEFINE OFF;
Insert into COOK.SCRAP (SCRAP_NO,MEMBER_ID,RECIPE_NO,SCRAP_DT) values (1,'id1',1,to_date('21/04/01','RR/MM/DD'));
Insert into COOK.SCRAP (SCRAP_NO,MEMBER_ID,RECIPE_NO,SCRAP_DT) values (2,'id1',2,to_date('21/04/01','RR/MM/DD'));
Insert into COOK.SCRAP (SCRAP_NO,MEMBER_ID,RECIPE_NO,SCRAP_DT) values (3,'id1',3,to_date('21/04/01','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SCRAP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COOK"."SCRAP_PK" ON "COOK"."SCRAP" ("MEMBER_ID", "RECIPE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SCRAP
--------------------------------------------------------

  ALTER TABLE "COOK"."SCRAP" ADD CONSTRAINT "SCRAP_PK" PRIMARY KEY ("MEMBER_ID", "RECIPE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "COOK"."SCRAP" MODIFY ("RECIPE_NO" NOT NULL ENABLE);
  ALTER TABLE "COOK"."SCRAP" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "COOK"."SCRAP" MODIFY ("SCRAP_NO" NOT NULL ENABLE);
